### ISSUE TITLE
character encoding of files (mixed utf-8 / utf-8 bom)

### ISSUE THREAD

**Issue by maybegeek** [vurdalakov/cms404#1]
Hi vurdalakov,

thanks for your work. Playing around I got following error in html validation:

`Non-space characters found without seeing a doctype first.`

All files for the creation of the final page should have `utf-8` and we better do not mix it with some `utf8 with bom` files. So changing the encoding of 

* `engine.php`
* `properties.php`
* `propertyclass.php`

to `utf-8 without bom` should help.

**Comment by vurdalakov** [comment]
Hi Christoph,
I merged your changes, thank you for your help!

**Comment by vurdalakov** [comment]
Fixed
